spring:
  application:
    name: car-provider-v2
dubbo:
  scan:
    base-packages: com.itheima.car.service.impl
  application:
    name: ${spring.application.name}
  protocol:
    port: 18083
    name: dubbo
    id: dubbo
  registry:
    #zookeeper
    address: zookeeper://127.0.0.1:2181
  provider:
    version: 1.0.0